/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

/**
 *
 * @author sheldon
 */
public class AlterarPessoaJuridica extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame2
     */
    public AlterarPessoaJuridica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAlteraNomePessoaJuridica = new javax.swing.JLabel();
        jtfAlteraNomePessoaJuridica = new javax.swing.JTextField();
        jlAlteraIdadePessoaJuridica = new javax.swing.JLabel();
        jtfAlteraIdadePessoaJuridica = new javax.swing.JTextField();
        jbAlterarPessoaJuridica = new javax.swing.JButton();
        jbAlteraCancelarPessoaJuridica = new javax.swing.JButton();
        jlAlteraCNPJpessoaJuridica = new javax.swing.JLabel();
        jtfAlteraCNPJpessoaJuridica = new javax.swing.JTextField();
        jlAlteraDataFudacaoPessoaJuridica = new javax.swing.JLabel();
        jtfAlteraDataFundacaoPessoaJuridica = new javax.swing.JTextField();
        jlAlteraEnderecoPessoaJuridica = new javax.swing.JLabel();
        jtfAlteraEnderecoPessoaJuridica = new javax.swing.JTextField();
        jlPesquisaPessoaJuridica = new javax.swing.JLabel();
        jtfPesquisaPessoaJuridica = new javax.swing.JTextField();
        jbPesquisaPessoaJuridica = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pessoa Juridica");

        jlAlteraNomePessoaJuridica.setText("Nome:");

        jtfAlteraNomePessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAlteraNomePessoaJuridicaActionPerformed(evt);
            }
        });

        jlAlteraIdadePessoaJuridica.setText("Idade:");

        jbAlterarPessoaJuridica.setText("Alterar");
        jbAlterarPessoaJuridica.setPreferredSize(new java.awt.Dimension(74, 29));
        jbAlterarPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarPessoaJuridicaActionPerformed(evt);
            }
        });

        jbAlteraCancelarPessoaJuridica.setText("Cancelar");
        jbAlteraCancelarPessoaJuridica.setPreferredSize(new java.awt.Dimension(74, 29));

        jlAlteraCNPJpessoaJuridica.setText("CNPJ:");

        jtfAlteraCNPJpessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAlteraCNPJpessoaJuridicaActionPerformed(evt);
            }
        });

        jlAlteraDataFudacaoPessoaJuridica.setText("Data de Fundação");

        jlAlteraEnderecoPessoaJuridica.setText("Endereço:");

        jlPesquisaPessoaJuridica.setText("Digite o CNPJ:");

        jbPesquisaPessoaJuridica.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbAlterarPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jbAlteraCancelarPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAlteraIdadePessoaJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAlteraIdadePessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAlteraCNPJpessoaJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAlteraCNPJpessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAlteraDataFudacaoPessoaJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAlteraDataFundacaoPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAlteraEnderecoPessoaJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAlteraEnderecoPessoaJuridica))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlAlteraNomePessoaJuridica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfAlteraNomePessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 146, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlPesquisaPessoaJuridica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfPesquisaPessoaJuridica)))
                                .addGap(18, 18, 18)
                                .addComponent(jbPesquisaPessoaJuridica)))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesquisaPessoaJuridica)
                    .addComponent(jtfPesquisaPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisaPessoaJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAlteraNomePessoaJuridica)
                    .addComponent(jtfAlteraNomePessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAlteraIdadePessoaJuridica)
                    .addComponent(jtfAlteraIdadePessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAlteraCNPJpessoaJuridica)
                    .addComponent(jtfAlteraCNPJpessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAlteraDataFudacaoPessoaJuridica)
                    .addComponent(jtfAlteraDataFundacaoPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAlteraEnderecoPessoaJuridica)
                    .addComponent(jtfAlteraEnderecoPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterarPessoaJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlteraCancelarPessoaJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        setBounds(0, 0, 600, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfAlteraNomePessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAlteraNomePessoaJuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAlteraNomePessoaJuridicaActionPerformed

    private void jbAlterarPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarPessoaJuridicaActionPerformed
        AlterarPessoaJuridica pFisica = new AlterarPessoaJuridica();
        
        pFisica.setVisible(false);
        
    }//GEN-LAST:event_jbAlterarPessoaJuridicaActionPerformed

    private void jtfAlteraCNPJpessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAlteraCNPJpessoaJuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAlteraCNPJpessoaJuridicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlteraCancelarPessoaJuridica;
    private javax.swing.JButton jbAlterarPessoaJuridica;
    private javax.swing.JButton jbPesquisaPessoaJuridica;
    private javax.swing.JLabel jlAlteraCNPJpessoaJuridica;
    private javax.swing.JLabel jlAlteraDataFudacaoPessoaJuridica;
    private javax.swing.JLabel jlAlteraEnderecoPessoaJuridica;
    private javax.swing.JLabel jlAlteraIdadePessoaJuridica;
    private javax.swing.JLabel jlAlteraNomePessoaJuridica;
    private javax.swing.JLabel jlPesquisaPessoaJuridica;
    private javax.swing.JTextField jtfAlteraCNPJpessoaJuridica;
    private javax.swing.JTextField jtfAlteraDataFundacaoPessoaJuridica;
    private javax.swing.JTextField jtfAlteraEnderecoPessoaJuridica;
    private javax.swing.JTextField jtfAlteraIdadePessoaJuridica;
    private javax.swing.JTextField jtfAlteraNomePessoaJuridica;
    private javax.swing.JTextField jtfPesquisaPessoaJuridica;
    // End of variables declaration//GEN-END:variables
}
