/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

/**
 *
 * @author sheldon
 */
public class PessoaFisica extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame2
     */
    public PessoaFisica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNomePessoaFisica = new javax.swing.JLabel();
        jtfNomePessoaFisica = new javax.swing.JTextField();
        jlIdadePessoaFisica = new javax.swing.JLabel();
        jtfIdadePessoaFisica = new javax.swing.JTextField();
        jbSalvarPessoaFisica = new javax.swing.JButton();
        jbCancelarPessoaFisica = new javax.swing.JButton();
        jlCPFpessoaFisica = new javax.swing.JLabel();
        jtfCPFpessoaFisica = new javax.swing.JTextField();
        jlDataNascimentoPessoaFisica = new javax.swing.JLabel();
        jtfDataNascimentoPessoaFisica = new javax.swing.JTextField();
        jlEnderecoPessoaFisica = new javax.swing.JLabel();
        jtfEnderecoPessoaFisica = new javax.swing.JTextField();
        jlSexoPessoaFisica = new javax.swing.JLabel();
        jcbSexoMasculinoPessoaFisica = new javax.swing.JCheckBox();
        jcbSexoFemininoPessoaFisica = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Pessoa Física");

        jlNomePessoaFisica.setText("Nome:");

        jtfNomePessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomePessoaFisicaActionPerformed(evt);
            }
        });

        jlIdadePessoaFisica.setText("Idade:");

        jbSalvarPessoaFisica.setText("Salvar");
        jbSalvarPessoaFisica.setPreferredSize(new java.awt.Dimension(74, 29));
        jbSalvarPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarPessoaFisicaActionPerformed(evt);
            }
        });

        jbCancelarPessoaFisica.setText("Cancelar");
        jbCancelarPessoaFisica.setPreferredSize(new java.awt.Dimension(74, 29));

        jlCPFpessoaFisica.setText("CPF:");

        jtfCPFpessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCPFpessoaFisicaActionPerformed(evt);
            }
        });

        jlDataNascimentoPessoaFisica.setText("Data de Nascimento:");

        jlEnderecoPessoaFisica.setText("Endereço:");

        jlSexoPessoaFisica.setText("Sexo:");

        jcbSexoMasculinoPessoaFisica.setText("Masculino");
        jcbSexoMasculinoPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSexoMasculinoPessoaFisicaActionPerformed(evt);
            }
        });

        jcbSexoFemininoPessoaFisica.setText("Feminino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlEnderecoPessoaFisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfEnderecoPessoaFisica))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlDataNascimentoPessoaFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfDataNascimentoPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlSexoPessoaFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbSexoMasculinoPessoaFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbSexoFemininoPessoaFisica)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlNomePessoaFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfNomePessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlCPFpessoaFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfCPFpessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlIdadePessoaFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfIdadePessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jbSalvarPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(jbCancelarPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomePessoaFisica)
                    .addComponent(jtfNomePessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdadePessoaFisica)
                    .addComponent(jtfIdadePessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexoPessoaFisica)
                    .addComponent(jcbSexoMasculinoPessoaFisica)
                    .addComponent(jcbSexoFemininoPessoaFisica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCPFpessoaFisica)
                    .addComponent(jtfCPFpessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataNascimentoPessoaFisica)
                    .addComponent(jtfDataNascimentoPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoPessoaFisica)
                    .addComponent(jtfEnderecoPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarPessoaFisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelarPessoaFisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        setBounds(0, 0, 602, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomePessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomePessoaFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomePessoaFisicaActionPerformed

    private void jbSalvarPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarPessoaFisicaActionPerformed
        PessoaFisica pFisica = new PessoaFisica();
        
        pFisica.setVisible(false);
        
    }//GEN-LAST:event_jbSalvarPessoaFisicaActionPerformed

    private void jtfCPFpessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCPFpessoaFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCPFpessoaFisicaActionPerformed

    private void jcbSexoMasculinoPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSexoMasculinoPessoaFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSexoMasculinoPessoaFisicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelarPessoaFisica;
    private javax.swing.JButton jbSalvarPessoaFisica;
    private javax.swing.JCheckBox jcbSexoFemininoPessoaFisica;
    private javax.swing.JCheckBox jcbSexoMasculinoPessoaFisica;
    private javax.swing.JLabel jlCPFpessoaFisica;
    private javax.swing.JLabel jlDataNascimentoPessoaFisica;
    private javax.swing.JLabel jlEnderecoPessoaFisica;
    private javax.swing.JLabel jlIdadePessoaFisica;
    private javax.swing.JLabel jlNomePessoaFisica;
    private javax.swing.JLabel jlSexoPessoaFisica;
    private javax.swing.JTextField jtfCPFpessoaFisica;
    private javax.swing.JTextField jtfDataNascimentoPessoaFisica;
    private javax.swing.JTextField jtfEnderecoPessoaFisica;
    private javax.swing.JTextField jtfIdadePessoaFisica;
    private javax.swing.JTextField jtfNomePessoaFisica;
    // End of variables declaration//GEN-END:variables
}
