/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

/**
 *
 * @author sheldon
 */
public class PessoaJuridica extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame2
     */
    public PessoaJuridica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNomePessoaJuridica = new javax.swing.JLabel();
        jtfNomePessoaJuridica = new javax.swing.JTextField();
        jlIdadePessoaJuridica = new javax.swing.JLabel();
        jtfIdadePessoaJuridica = new javax.swing.JTextField();
        jbSalvarPessoaJuridica = new javax.swing.JButton();
        jbCancelarPessoaJuridica = new javax.swing.JButton();
        jlCNPJpessoaJuridica = new javax.swing.JLabel();
        jtfCNPJpessoaJuridica = new javax.swing.JTextField();
        jlDataFudacaoPessoaJuridica = new javax.swing.JLabel();
        jtfDataFundacaoPessoaJuridica = new javax.swing.JTextField();
        jlEnderecoPessoaJuridica = new javax.swing.JLabel();
        jtfEnderecoPessoaJuridica = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Pessoa Juridica");

        jlNomePessoaJuridica.setText("Nome:");

        jtfNomePessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomePessoaJuridicaActionPerformed(evt);
            }
        });

        jlIdadePessoaJuridica.setText("Idade:");

        jbSalvarPessoaJuridica.setText("Salvar");
        jbSalvarPessoaJuridica.setPreferredSize(new java.awt.Dimension(74, 29));
        jbSalvarPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarPessoaJuridicaActionPerformed(evt);
            }
        });

        jbCancelarPessoaJuridica.setText("Cancelar");
        jbCancelarPessoaJuridica.setPreferredSize(new java.awt.Dimension(74, 29));

        jlCNPJpessoaJuridica.setText("CNPJ:");

        jtfCNPJpessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCNPJpessoaJuridicaActionPerformed(evt);
            }
        });

        jlDataFudacaoPessoaJuridica.setText("Data de Fundação");

        jlEnderecoPessoaJuridica.setText("Endereço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlEnderecoPessoaJuridica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEnderecoPessoaJuridica))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlNomePessoaJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomePessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlIdadePessoaJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfIdadePessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCNPJpessoaJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCNPJpessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlDataFudacaoPessoaJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDataFundacaoPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbSalvarPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jbCancelarPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomePessoaJuridica)
                    .addComponent(jtfNomePessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdadePessoaJuridica)
                    .addComponent(jtfIdadePessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCNPJpessoaJuridica)
                    .addComponent(jtfCNPJpessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataFudacaoPessoaJuridica)
                    .addComponent(jtfDataFundacaoPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoPessoaJuridica)
                    .addComponent(jtfEnderecoPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarPessoaJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelarPessoaJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        setBounds(0, 0, 527, 343);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomePessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomePessoaJuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomePessoaJuridicaActionPerformed

    private void jbSalvarPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarPessoaJuridicaActionPerformed
        PessoaJuridica pFisica = new PessoaJuridica();
        
        pFisica.setVisible(false);
        
    }//GEN-LAST:event_jbSalvarPessoaJuridicaActionPerformed

    private void jtfCNPJpessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCNPJpessoaJuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCNPJpessoaJuridicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelarPessoaJuridica;
    private javax.swing.JButton jbSalvarPessoaJuridica;
    private javax.swing.JLabel jlCNPJpessoaJuridica;
    private javax.swing.JLabel jlDataFudacaoPessoaJuridica;
    private javax.swing.JLabel jlEnderecoPessoaJuridica;
    private javax.swing.JLabel jlIdadePessoaJuridica;
    private javax.swing.JLabel jlNomePessoaJuridica;
    private javax.swing.JTextField jtfCNPJpessoaJuridica;
    private javax.swing.JTextField jtfDataFundacaoPessoaJuridica;
    private javax.swing.JTextField jtfEnderecoPessoaJuridica;
    private javax.swing.JTextField jtfIdadePessoaJuridica;
    private javax.swing.JTextField jtfNomePessoaJuridica;
    // End of variables declaration//GEN-END:variables
}
